import { createFileRoute } from "@tanstack/react-router";
import { LegalPage, LegalSection, LegalList, LegalCallout } from "@/components/layout/LegalPage";

export const Route = createFileRoute("/data-sources")({
  head: () => ({
    meta: [
      { title: "Data Sources — ErfStoep" },
      { name: "description", content: "Where ErfStoep obtains property data, how we use it, and the limits of its accuracy and completeness." },
    ],
  }),
  component: DataSourcesPage,
});

function DataSourcesPage() {
  return (
    <LegalPage
      title="Data Sources"
      intro="ErfStoep combines multiple data sources to produce property intelligence. This page explains where the data comes from and its limits."
    >
      <LegalSection title="Where Our Data Comes From">
        <p>ErfStoep may obtain information from:</p>
        <LegalList items={[
          "public records",
          "municipal records",
          "licensed data providers",
          "geospatial datasets",
          "mapping providers",
          "user submissions",
          "automated analysis",
        ]} />
      </LegalSection>

      <LegalSection title="Coverage and Availability">
        <p>
          Data availability varies by property and location. Some properties may have rich
          historical and ownership data while others have very little. Coverage is being
          expanded over time.
        </p>
      </LegalSection>

      <LegalSection title="Accuracy and Completeness">
        <p>
          ErfStoep does not guarantee accuracy or completeness. Records may be delayed,
          incomplete, estimated, or out of date. Users should independently verify any
          information that materially affects a decision.
        </p>
      </LegalSection>

      <LegalSection title="Estimates and Modelling">
        <p>
          Where ErfStoep shows an estimated value, the figure is generated by an
          automated model using available data and modelling assumptions. It is not a
          certified valuation or appraisal.
        </p>
        <LegalCallout>
          <strong>Estimate Only • Not a Certified Valuation</strong>
        </LegalCallout>
      </LegalSection>

      <LegalSection title="Demo Data">
        <p>
          During the pilot, parts of the platform display mock data for demonstration
          purposes. Mock data is clearly marked with a visible "Demo Data" badge.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
