/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyRouteImport } from './routes/why'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PartnershipsRouteImport } from './routes/partnerships'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForInvestorsRouteImport } from './routes/for-investors'
import { Route as ForHomeownersRouteImport } from './routes/for-homeowners'
import { Route as ForDevelopersRouteImport } from './routes/for-developers'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/admin_.users'
import { Route as AdminEntitlementsRouteImport } from './routes/admin_.entitlements'
import { Route as AdminReadinessRouteImport } from './routes/admin.readiness'
import { Route as AdminPublicDataDebugRouteImport } from './routes/admin.public-data-debug'
import { Route as ApiSitePotentialRetryPackRouteImport } from './routes/api/site-potential.retry-pack'
import { Route as ApiSitePotentialProcessRouteImport } from './routes/api/site-potential.process'
import { Route as ApiSitePotentialPackStatusRouteImport } from './routes/api/site-potential.pack-status'
import { Route as ApiSitePotentialGenerateRouteImport } from './routes/api/site-potential.generate'
import { Route as ApiSitePotentialDevEntitlementRouteImport } from './routes/api/site-potential.dev-entitlement'
import { Route as ApiSitePotentialBetaStatusRouteImport } from './routes/api/site-potential.beta-status'
import { Route as ApiSitePotentialBetaRequestRouteImport } from './routes/api/site-potential.beta-request'
import { Route as ApiSitePotentialBetaRedeemRouteImport } from './routes/api/site-potential.beta-redeem'
import { Route as ApiSitePotentialBetaGrantRouteImport } from './routes/api/site-potential.beta-grant'
import { Route as ApiReportsAskEasyErfRouteImport } from './routes/api/reports.ask-easy-erf'
import { Route as ApiLocalServicesSearchRouteImport } from './routes/api/local-services.search'
import { Route as ApiListingsImportRouteImport } from './routes/api/listings.import'
import { Route as ApiAdminSupportRouteImport } from './routes/api/admin.support'
import { Route as ApiAddressSuggestionsRouteImport } from './routes/api/address.suggestions'
import { Route as ApiPublicSitePotentialProcessRouteImport } from './routes/api/public.site-potential.process'

const WhyRoute = WhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsRoute = PartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForInvestorsRoute = ForInvestorsRouteImport.update({
  id: '/for-investors',
  path: '/for-investors',
  getParentRoute: () => rootRouteImport,
} as any)
const ForHomeownersRoute = ForHomeownersRouteImport.update({
  id: '/for-homeowners',
  path: '/for-homeowners',
  getParentRoute: () => rootRouteImport,
} as any)
const ForDevelopersRoute = ForDevelopersRouteImport.update({
  id: '/for-developers',
  path: '/for-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin_/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEntitlementsRoute = AdminEntitlementsRouteImport.update({
  id: '/admin_/entitlements',
  path: '/admin/entitlements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReadinessRoute = AdminReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPublicDataDebugRoute = AdminPublicDataDebugRouteImport.update({
  id: '/public-data-debug',
  path: '/public-data-debug',
  getParentRoute: () => AdminRoute,
} as any)
const ApiSitePotentialRetryPackRoute =
  ApiSitePotentialRetryPackRouteImport.update({
    id: '/api/site-potential/retry-pack',
    path: '/api/site-potential/retry-pack',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSitePotentialProcessRoute = ApiSitePotentialProcessRouteImport.update({
  id: '/api/site-potential/process',
  path: '/api/site-potential/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitePotentialPackStatusRoute =
  ApiSitePotentialPackStatusRouteImport.update({
    id: '/api/site-potential/pack-status',
    path: '/api/site-potential/pack-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSitePotentialGenerateRoute =
  ApiSitePotentialGenerateRouteImport.update({
    id: '/api/site-potential/generate',
    path: '/api/site-potential/generate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSitePotentialDevEntitlementRoute =
  ApiSitePotentialDevEntitlementRouteImport.update({
    id: '/api/site-potential/dev-entitlement',
    path: '/api/site-potential/dev-entitlement',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSitePotentialBetaStatusRoute =
  ApiSitePotentialBetaStatusRouteImport.update({
    id: '/api/site-potential/beta-status',
    path: '/api/site-potential/beta-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSitePotentialBetaRequestRoute =
  ApiSitePotentialBetaRequestRouteImport.update({
    id: '/api/site-potential/beta-request',
    path: '/api/site-potential/beta-request',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSitePotentialBetaRedeemRoute =
  ApiSitePotentialBetaRedeemRouteImport.update({
    id: '/api/site-potential/beta-redeem',
    path: '/api/site-potential/beta-redeem',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSitePotentialBetaGrantRoute =
  ApiSitePotentialBetaGrantRouteImport.update({
    id: '/api/site-potential/beta-grant',
    path: '/api/site-potential/beta-grant',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiReportsAskEasyErfRoute = ApiReportsAskEasyErfRouteImport.update({
  id: '/api/reports/ask-easy-erf',
  path: '/api/reports/ask-easy-erf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocalServicesSearchRoute = ApiLocalServicesSearchRouteImport.update({
  id: '/api/local-services/search',
  path: '/api/local-services/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListingsImportRoute = ApiListingsImportRouteImport.update({
  id: '/api/listings/import',
  path: '/api/listings/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSupportRoute = ApiAdminSupportRouteImport.update({
  id: '/api/admin/support',
  path: '/api/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAddressSuggestionsRoute = ApiAddressSuggestionsRouteImport.update({
  id: '/api/address/suggestions',
  path: '/api/address/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSitePotentialProcessRoute =
  ApiPublicSitePotentialProcessRouteImport.update({
    id: '/api/public/site-potential/process',
    path: '/api/public/site-potential/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/for-developers': typeof ForDevelopersRoute
  '/for-homeowners': typeof ForHomeownersRoute
  '/for-investors': typeof ForInvestorsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/partnerships': typeof PartnershipsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/roadmap': typeof RoadmapRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/terms': typeof TermsRoute
  '/why': typeof WhyRoute
  '/admin/public-data-debug': typeof AdminPublicDataDebugRoute
  '/admin/readiness': typeof AdminReadinessRoute
  '/admin/entitlements': typeof AdminEntitlementsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/address/suggestions': typeof ApiAddressSuggestionsRoute
  '/api/admin/support': typeof ApiAdminSupportRoute
  '/api/listings/import': typeof ApiListingsImportRoute
  '/api/local-services/search': typeof ApiLocalServicesSearchRoute
  '/api/reports/ask-easy-erf': typeof ApiReportsAskEasyErfRoute
  '/api/site-potential/beta-grant': typeof ApiSitePotentialBetaGrantRoute
  '/api/site-potential/beta-redeem': typeof ApiSitePotentialBetaRedeemRoute
  '/api/site-potential/beta-request': typeof ApiSitePotentialBetaRequestRoute
  '/api/site-potential/beta-status': typeof ApiSitePotentialBetaStatusRoute
  '/api/site-potential/dev-entitlement': typeof ApiSitePotentialDevEntitlementRoute
  '/api/site-potential/generate': typeof ApiSitePotentialGenerateRoute
  '/api/site-potential/pack-status': typeof ApiSitePotentialPackStatusRoute
  '/api/site-potential/process': typeof ApiSitePotentialProcessRoute
  '/api/site-potential/retry-pack': typeof ApiSitePotentialRetryPackRoute
  '/api/public/site-potential/process': typeof ApiPublicSitePotentialProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/for-developers': typeof ForDevelopersRoute
  '/for-homeowners': typeof ForHomeownersRoute
  '/for-investors': typeof ForInvestorsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/partnerships': typeof PartnershipsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/roadmap': typeof RoadmapRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/terms': typeof TermsRoute
  '/why': typeof WhyRoute
  '/admin/public-data-debug': typeof AdminPublicDataDebugRoute
  '/admin/readiness': typeof AdminReadinessRoute
  '/admin/entitlements': typeof AdminEntitlementsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/address/suggestions': typeof ApiAddressSuggestionsRoute
  '/api/admin/support': typeof ApiAdminSupportRoute
  '/api/listings/import': typeof ApiListingsImportRoute
  '/api/local-services/search': typeof ApiLocalServicesSearchRoute
  '/api/reports/ask-easy-erf': typeof ApiReportsAskEasyErfRoute
  '/api/site-potential/beta-grant': typeof ApiSitePotentialBetaGrantRoute
  '/api/site-potential/beta-redeem': typeof ApiSitePotentialBetaRedeemRoute
  '/api/site-potential/beta-request': typeof ApiSitePotentialBetaRequestRoute
  '/api/site-potential/beta-status': typeof ApiSitePotentialBetaStatusRoute
  '/api/site-potential/dev-entitlement': typeof ApiSitePotentialDevEntitlementRoute
  '/api/site-potential/generate': typeof ApiSitePotentialGenerateRoute
  '/api/site-potential/pack-status': typeof ApiSitePotentialPackStatusRoute
  '/api/site-potential/process': typeof ApiSitePotentialProcessRoute
  '/api/site-potential/retry-pack': typeof ApiSitePotentialRetryPackRoute
  '/api/public/site-potential/process': typeof ApiPublicSitePotentialProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/for-developers': typeof ForDevelopersRoute
  '/for-homeowners': typeof ForHomeownersRoute
  '/for-investors': typeof ForInvestorsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/partnerships': typeof PartnershipsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/roadmap': typeof RoadmapRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/terms': typeof TermsRoute
  '/why': typeof WhyRoute
  '/admin/public-data-debug': typeof AdminPublicDataDebugRoute
  '/admin/readiness': typeof AdminReadinessRoute
  '/admin_/entitlements': typeof AdminEntitlementsRoute
  '/admin_/users': typeof AdminUsersRoute
  '/api/address/suggestions': typeof ApiAddressSuggestionsRoute
  '/api/admin/support': typeof ApiAdminSupportRoute
  '/api/listings/import': typeof ApiListingsImportRoute
  '/api/local-services/search': typeof ApiLocalServicesSearchRoute
  '/api/reports/ask-easy-erf': typeof ApiReportsAskEasyErfRoute
  '/api/site-potential/beta-grant': typeof ApiSitePotentialBetaGrantRoute
  '/api/site-potential/beta-redeem': typeof ApiSitePotentialBetaRedeemRoute
  '/api/site-potential/beta-request': typeof ApiSitePotentialBetaRequestRoute
  '/api/site-potential/beta-status': typeof ApiSitePotentialBetaStatusRoute
  '/api/site-potential/dev-entitlement': typeof ApiSitePotentialDevEntitlementRoute
  '/api/site-potential/generate': typeof ApiSitePotentialGenerateRoute
  '/api/site-potential/pack-status': typeof ApiSitePotentialPackStatusRoute
  '/api/site-potential/process': typeof ApiSitePotentialProcessRoute
  '/api/site-potential/retry-pack': typeof ApiSitePotentialRetryPackRoute
  '/api/public/site-potential/process': typeof ApiPublicSitePotentialProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/data-sources'
    | '/disclaimer'
    | '/faq'
    | '/features'
    | '/for-developers'
    | '/for-homeowners'
    | '/for-investors'
    | '/how-it-works'
    | '/partnerships'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/reports'
    | '/roadmap'
    | '/subscriptions'
    | '/terms'
    | '/why'
    | '/admin/public-data-debug'
    | '/admin/readiness'
    | '/admin/entitlements'
    | '/admin/users'
    | '/api/address/suggestions'
    | '/api/admin/support'
    | '/api/listings/import'
    | '/api/local-services/search'
    | '/api/reports/ask-easy-erf'
    | '/api/site-potential/beta-grant'
    | '/api/site-potential/beta-redeem'
    | '/api/site-potential/beta-request'
    | '/api/site-potential/beta-status'
    | '/api/site-potential/dev-entitlement'
    | '/api/site-potential/generate'
    | '/api/site-potential/pack-status'
    | '/api/site-potential/process'
    | '/api/site-potential/retry-pack'
    | '/api/public/site-potential/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/data-sources'
    | '/disclaimer'
    | '/faq'
    | '/features'
    | '/for-developers'
    | '/for-homeowners'
    | '/for-investors'
    | '/how-it-works'
    | '/partnerships'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/reports'
    | '/roadmap'
    | '/subscriptions'
    | '/terms'
    | '/why'
    | '/admin/public-data-debug'
    | '/admin/readiness'
    | '/admin/entitlements'
    | '/admin/users'
    | '/api/address/suggestions'
    | '/api/admin/support'
    | '/api/listings/import'
    | '/api/local-services/search'
    | '/api/reports/ask-easy-erf'
    | '/api/site-potential/beta-grant'
    | '/api/site-potential/beta-redeem'
    | '/api/site-potential/beta-request'
    | '/api/site-potential/beta-status'
    | '/api/site-potential/dev-entitlement'
    | '/api/site-potential/generate'
    | '/api/site-potential/pack-status'
    | '/api/site-potential/process'
    | '/api/site-potential/retry-pack'
    | '/api/public/site-potential/process'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/data-sources'
    | '/disclaimer'
    | '/faq'
    | '/features'
    | '/for-developers'
    | '/for-homeowners'
    | '/for-investors'
    | '/how-it-works'
    | '/partnerships'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/reports'
    | '/roadmap'
    | '/subscriptions'
    | '/terms'
    | '/why'
    | '/admin/public-data-debug'
    | '/admin/readiness'
    | '/admin_/entitlements'
    | '/admin_/users'
    | '/api/address/suggestions'
    | '/api/admin/support'
    | '/api/listings/import'
    | '/api/local-services/search'
    | '/api/reports/ask-easy-erf'
    | '/api/site-potential/beta-grant'
    | '/api/site-potential/beta-redeem'
    | '/api/site-potential/beta-request'
    | '/api/site-potential/beta-status'
    | '/api/site-potential/dev-entitlement'
    | '/api/site-potential/generate'
    | '/api/site-potential/pack-status'
    | '/api/site-potential/process'
    | '/api/site-potential/retry-pack'
    | '/api/public/site-potential/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DataSourcesRoute: typeof DataSourcesRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  ForDevelopersRoute: typeof ForDevelopersRoute
  ForHomeownersRoute: typeof ForHomeownersRoute
  ForInvestorsRoute: typeof ForInvestorsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PartnershipsRoute: typeof PartnershipsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  RoadmapRoute: typeof RoadmapRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  TermsRoute: typeof TermsRoute
  WhyRoute: typeof WhyRoute
  AdminEntitlementsRoute: typeof AdminEntitlementsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiAddressSuggestionsRoute: typeof ApiAddressSuggestionsRoute
  ApiAdminSupportRoute: typeof ApiAdminSupportRoute
  ApiListingsImportRoute: typeof ApiListingsImportRoute
  ApiLocalServicesSearchRoute: typeof ApiLocalServicesSearchRoute
  ApiReportsAskEasyErfRoute: typeof ApiReportsAskEasyErfRoute
  ApiSitePotentialBetaGrantRoute: typeof ApiSitePotentialBetaGrantRoute
  ApiSitePotentialBetaRedeemRoute: typeof ApiSitePotentialBetaRedeemRoute
  ApiSitePotentialBetaRequestRoute: typeof ApiSitePotentialBetaRequestRoute
  ApiSitePotentialBetaStatusRoute: typeof ApiSitePotentialBetaStatusRoute
  ApiSitePotentialDevEntitlementRoute: typeof ApiSitePotentialDevEntitlementRoute
  ApiSitePotentialGenerateRoute: typeof ApiSitePotentialGenerateRoute
  ApiSitePotentialPackStatusRoute: typeof ApiSitePotentialPackStatusRoute
  ApiSitePotentialProcessRoute: typeof ApiSitePotentialProcessRoute
  ApiSitePotentialRetryPackRoute: typeof ApiSitePotentialRetryPackRoute
  ApiPublicSitePotentialProcessRoute: typeof ApiPublicSitePotentialProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why': {
      id: '/why'
      path: '/why'
      fullPath: '/why'
      preLoaderRoute: typeof WhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships': {
      id: '/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof PartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-investors': {
      id: '/for-investors'
      path: '/for-investors'
      fullPath: '/for-investors'
      preLoaderRoute: typeof ForInvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-homeowners': {
      id: '/for-homeowners'
      path: '/for-homeowners'
      fullPath: '/for-homeowners'
      preLoaderRoute: typeof ForHomeownersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-developers': {
      id: '/for-developers'
      path: '/for-developers'
      fullPath: '/for-developers'
      preLoaderRoute: typeof ForDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/users': {
      id: '/admin_/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/entitlements': {
      id: '/admin_/entitlements'
      path: '/admin/entitlements'
      fullPath: '/admin/entitlements'
      preLoaderRoute: typeof AdminEntitlementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/readiness': {
      id: '/admin/readiness'
      path: '/readiness'
      fullPath: '/admin/readiness'
      preLoaderRoute: typeof AdminReadinessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/public-data-debug': {
      id: '/admin/public-data-debug'
      path: '/public-data-debug'
      fullPath: '/admin/public-data-debug'
      preLoaderRoute: typeof AdminPublicDataDebugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/site-potential/retry-pack': {
      id: '/api/site-potential/retry-pack'
      path: '/api/site-potential/retry-pack'
      fullPath: '/api/site-potential/retry-pack'
      preLoaderRoute: typeof ApiSitePotentialRetryPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site-potential/process': {
      id: '/api/site-potential/process'
      path: '/api/site-potential/process'
      fullPath: '/api/site-potential/process'
      preLoaderRoute: typeof ApiSitePotentialProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site-potential/pack-status': {
      id: '/api/site-potential/pack-status'
      path: '/api/site-potential/pack-status'
      fullPath: '/api/site-potential/pack-status'
      preLoaderRoute: typeof ApiSitePotentialPackStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site-potential/generate': {
      id: '/api/site-potential/generate'
      path: '/api/site-potential/generate'
      fullPath: '/api/site-potential/generate'
      preLoaderRoute: typeof ApiSitePotentialGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site-potential/dev-entitlement': {
      id: '/api/site-potential/dev-entitlement'
      path: '/api/site-potential/dev-entitlement'
      fullPath: '/api/site-potential/dev-entitlement'
      preLoaderRoute: typeof ApiSitePotentialDevEntitlementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site-potential/beta-status': {
      id: '/api/site-potential/beta-status'
      path: '/api/site-potential/beta-status'
      fullPath: '/api/site-potential/beta-status'
      preLoaderRoute: typeof ApiSitePotentialBetaStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site-potential/beta-request': {
      id: '/api/site-potential/beta-request'
      path: '/api/site-potential/beta-request'
      fullPath: '/api/site-potential/beta-request'
      preLoaderRoute: typeof ApiSitePotentialBetaRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site-potential/beta-redeem': {
      id: '/api/site-potential/beta-redeem'
      path: '/api/site-potential/beta-redeem'
      fullPath: '/api/site-potential/beta-redeem'
      preLoaderRoute: typeof ApiSitePotentialBetaRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site-potential/beta-grant': {
      id: '/api/site-potential/beta-grant'
      path: '/api/site-potential/beta-grant'
      fullPath: '/api/site-potential/beta-grant'
      preLoaderRoute: typeof ApiSitePotentialBetaGrantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/ask-easy-erf': {
      id: '/api/reports/ask-easy-erf'
      path: '/api/reports/ask-easy-erf'
      fullPath: '/api/reports/ask-easy-erf'
      preLoaderRoute: typeof ApiReportsAskEasyErfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/local-services/search': {
      id: '/api/local-services/search'
      path: '/api/local-services/search'
      fullPath: '/api/local-services/search'
      preLoaderRoute: typeof ApiLocalServicesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/listings/import': {
      id: '/api/listings/import'
      path: '/api/listings/import'
      fullPath: '/api/listings/import'
      preLoaderRoute: typeof ApiListingsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/support': {
      id: '/api/admin/support'
      path: '/api/admin/support'
      fullPath: '/api/admin/support'
      preLoaderRoute: typeof ApiAdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/address/suggestions': {
      id: '/api/address/suggestions'
      path: '/api/address/suggestions'
      fullPath: '/api/address/suggestions'
      preLoaderRoute: typeof ApiAddressSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/site-potential/process': {
      id: '/api/public/site-potential/process'
      path: '/api/public/site-potential/process'
      fullPath: '/api/public/site-potential/process'
      preLoaderRoute: typeof ApiPublicSitePotentialProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminPublicDataDebugRoute: typeof AdminPublicDataDebugRoute
  AdminReadinessRoute: typeof AdminReadinessRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPublicDataDebugRoute: AdminPublicDataDebugRoute,
  AdminReadinessRoute: AdminReadinessRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DataSourcesRoute: DataSourcesRoute,
  DisclaimerRoute: DisclaimerRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  ForDevelopersRoute: ForDevelopersRoute,
  ForHomeownersRoute: ForHomeownersRoute,
  ForInvestorsRoute: ForInvestorsRoute,
  HowItWorksRoute: HowItWorksRoute,
  PartnershipsRoute: PartnershipsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  RoadmapRoute: RoadmapRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  TermsRoute: TermsRoute,
  WhyRoute: WhyRoute,
  AdminEntitlementsRoute: AdminEntitlementsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiAddressSuggestionsRoute: ApiAddressSuggestionsRoute,
  ApiAdminSupportRoute: ApiAdminSupportRoute,
  ApiListingsImportRoute: ApiListingsImportRoute,
  ApiLocalServicesSearchRoute: ApiLocalServicesSearchRoute,
  ApiReportsAskEasyErfRoute: ApiReportsAskEasyErfRoute,
  ApiSitePotentialBetaGrantRoute: ApiSitePotentialBetaGrantRoute,
  ApiSitePotentialBetaRedeemRoute: ApiSitePotentialBetaRedeemRoute,
  ApiSitePotentialBetaRequestRoute: ApiSitePotentialBetaRequestRoute,
  ApiSitePotentialBetaStatusRoute: ApiSitePotentialBetaStatusRoute,
  ApiSitePotentialDevEntitlementRoute: ApiSitePotentialDevEntitlementRoute,
  ApiSitePotentialGenerateRoute: ApiSitePotentialGenerateRoute,
  ApiSitePotentialPackStatusRoute: ApiSitePotentialPackStatusRoute,
  ApiSitePotentialProcessRoute: ApiSitePotentialProcessRoute,
  ApiSitePotentialRetryPackRoute: ApiSitePotentialRetryPackRoute,
  ApiPublicSitePotentialProcessRoute: ApiPublicSitePotentialProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
